package discover

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/danilopopovikj/wassup/internal/model"
	"github.com/danilopopovikj/wassup/internal/probe/k8s"
)

// The production fixture is a repository shaped like a real one: a
// Kustomize base with a production and a local overlay, settings in a
// ConfigMap the Deployments load with envFrom, passwords written in plain
// in the manifests, an Ingress with several paths, an observability stack
// made of five workloads, and buckets whose names are Terraform
// expressions.

// secrets are the credentials written in plain in the production fixture
// and in the live inventory below. None of them may be written or printed.
var secrets = []string{
	"Pg-Pa55-7f3a",     // POSTGRES_PASSWORD, and in a URL in the arguments
	"Ch-Pa55-c0ffee",   // CLICKHOUSE_PASSWORD
	"Ch-Dsn-Pa55-9d41", // in the query of CLICKHOUSE_DSN, from a ConfigMap
	"R3dis-Pa55-e2c1",  // in a URL generated by Kustomize
	"wk-live-5b1f77",   // WORKER_API_KEY, generated by Kustomize
	"Adm1n", "44e0",    // --admin-password "Adm1n Pa55 44e0", an argument with blanks
	"L1ve-Pg-Pa55-81aa",  // live pod spec, POSTGRES_PASSWORD
	"L1ve-Ch-Dsn-52c9",   // live pod spec, CLICKHOUSE_DSN
	"L1ve-Tok-99f1",      // live pod spec, command line
	"live-user:L1ve-Url", // live pod spec, user and password of a URL
}

func scanProduction(t *testing.T) *Findings {
	t.Helper()
	f, err := Scan(Options{Root: "testdata/production"})
	if err != nil {
		t.Fatal(err)
	}
	return f
}

// liveInventory is what the cluster of the production fixture reports. The
// environment values are written as a pod spec holds them, in plain: the
// inventory k8s.Discover returns is already reduced (its own test checks
// that), and AddCluster must not depend on it.
func liveInventory() *k8s.Inventory {
	return &k8s.Inventory{
		Context:    "bookstore-prod",
		Namespaces: []string{"app", "platform"},
		Nodes: []k8s.NodeInfo{
			{Name: "node-1", Ready: true}, {Name: "node-2", Ready: true}, {Name: "node-3", Ready: true},
			{Name: "node-4", Ready: true, Taints: []string{"dedicated=db:NoSchedule"}},
		},
		Workloads: []k8s.WorkloadInfo{
			{Namespace: "app", Kind: "Deployment", Name: "backend", Selector: "app=bookstore-backend", Images: []string{"ghcr.io/bookstore/backend:4.1.0"},
				Nodes: []string{"node-1", "node-3"}, Labels: map[string]string{"app": "bookstore-backend"},
				Command: []string{"backend: uvicorn app.main:app --api-token L1ve-Tok-99f1 --db postgresql://live-user:L1ve-Url@app-db-rw:5432/bookstore"},
				Env: []k8s.EnvRef{
					{Container: "backend", Name: "POSTGRES_SERVER", Value: "app-db-rw", ConfigRef: "app-config/POSTGRES_SERVER"},
					{Container: "backend", Name: "POSTGRES_PASSWORD", Value: "L1ve-Pg-Pa55-81aa"},
					{Container: "backend", Name: "CLICKHOUSE_DSN", Value: "tcp://signoz-clickhouse.platform:9000/?username=admin&password=L1ve-Ch-Dsn-52c9"},
					{Container: "backend", Name: "CACHE_HOST", Value: "cache", ConfigRef: "app-config/CACHE_HOST"},
					{Container: "backend", Name: "ELECTRIC_URL", Value: "http://electric.app:3000", ConfigRef: "app-config/ELECTRIC_URL"},
					{Container: "backend", Name: "HATCHET_CLIENT_HOST_PORT", Value: "hatchet-engine.app:7070", ConfigRef: "app-config/HATCHET_CLIENT_HOST_PORT"},
					{Container: "backend", Name: "OTEL_EXPORTER_OTLP_ENDPOINT", Value: "http://signoz-otel-collector.platform:4317"},
					{Container: "backend", Name: "HATCHET_CLIENT_TOKEN", SecretRef: "hatchet/token"},
					{Container: "backend", Name: "*", SecretRef: "app-secrets/*"},
				}},
			{Namespace: "app", Kind: "Deployment", Name: "cache", Selector: "app=cache", Images: []string{"valkey/valkey:8"}, Nodes: []string{"node-2"}, Labels: map[string]string{"app": "cache"}},
			{Namespace: "app", Kind: "Deployment", Name: "app-electric", Selector: "app=app-electric", Images: []string{"electricsql/electric:1.0.0"}, Nodes: []string{"node-2"},
				Labels: map[string]string{"app": "app-electric"},
				Env:    []k8s.EnvRef{{Container: "electric", Name: "DATABASE_URL", Value: "postgresql://app-db-rw.app:5432"}}},
			{Namespace: "app", Kind: "Deployment", Name: "hatchet-engine", Selector: "app=hatchet-engine", Images: []string{"ghcr.io/hatchet-dev/hatchet-engine:v0.62.1"}, Labels: map[string]string{"app": "hatchet-engine"}},
			{Namespace: "app", Kind: "Deployment", Name: "hatchet-api", Selector: "app=hatchet-api", Images: []string{"ghcr.io/hatchet-dev/hatchet-api:v0.62.1"}, Labels: map[string]string{"app": "hatchet-api"}},
			{Namespace: "platform", Kind: "Deployment", Name: "signoz", Images: []string{"signoz/signoz:0.50.0"}, Nodes: []string{"node-3"},
				Labels: map[string]string{"app.kubernetes.io/name": "signoz", "app.kubernetes.io/instance": "signoz"}, Release: "signoz"},
			{Namespace: "platform", Kind: "Deployment", Name: "signoz-otel-collector", Images: []string{"signoz/signoz-otel-collector:0.111.0"}, Nodes: []string{"node-1"},
				Labels: map[string]string{"app.kubernetes.io/name": "otel-collector", "app.kubernetes.io/instance": "signoz"}, Release: "signoz"},
			{Namespace: "platform", Kind: "StatefulSet", Name: "signoz-zookeeper", Images: []string{"bitnami/zookeeper:3.9"}, Nodes: []string{"node-2"},
				Labels: map[string]string{"app.kubernetes.io/name": "zookeeper", "app.kubernetes.io/instance": "signoz"}, Release: "signoz"},
			{Namespace: "platform", Kind: "StatefulSet", Name: "chi-signoz-clickhouse-cluster-0-0", Images: []string{"clickhouse/clickhouse-server:24.1"}, Nodes: []string{"node-2"},
				Labels: map[string]string{"clickhouse.altinity.com/chi": "signoz-clickhouse"}},
			{Namespace: "platform", Kind: "DaemonSet", Name: "signoz-k8s-infra-otel-agent", Images: []string{"otel/opentelemetry-collector-contrib:0.109.0"}, Nodes: []string{"node-1", "node-2", "node-3", "node-4"},
				Labels: map[string]string{"app.kubernetes.io/name": "otel-agent", "app.kubernetes.io/instance": "signoz-k8s-infra"}, Release: "signoz-k8s-infra"},
		},
		Services: []k8s.ServiceInfo{
			{Namespace: "app", Name: "backend", Selector: "app=bookstore-backend"},
			{Namespace: "app", Name: "cache", Selector: "app=cache"},
			{Namespace: "app", Name: "electric", Selector: "app=app-electric"},
			{Namespace: "app", Name: "hatchet-engine", Selector: "app=hatchet-engine"},
			{Namespace: "app", Name: "hatchet-api", Selector: "app=hatchet-api"},
			{Namespace: "app", Name: "app-db-rw", Selector: "cnpg.io/cluster=app-db,role=primary"},
			{Namespace: "platform", Name: "signoz", Selector: "app.kubernetes.io/name=signoz"},
			{Namespace: "platform", Name: "signoz-otel-collector", Selector: "app.kubernetes.io/name=otel-collector"},
			{Namespace: "platform", Name: "signoz-clickhouse", Selector: "clickhouse.altinity.com/chi=signoz-clickhouse"},
		},
		Ingresses: []k8s.IngressInfo{
			{Namespace: "kube-system", Name: "adminer", Hosts: []string{"adminer.bookstore.example"}, Backends: []string{"adminer:8080"}, Services: []string{"adminer"}},
			{Namespace: "app", Name: "web", Hosts: []string{"app.bookstore.example"},
				Backends: []string{"backend:8000 /api/v1/login", "backend:8000 /api/v1/items", "backend:8000", "electric:3000 /shapes"}, Services: []string{"backend", "electric"}},
		},
		CNPGClusters: []k8s.CNPGInfo{{Namespace: "app", Name: "app-db", Instances: 2, Ready: 2, Primary: "app-db-1"}},
	}
}

// liveProposal is the proposal of a run against the live cluster alone.
func liveProposal(t *testing.T) (*Findings, *Proposal) {
	t.Helper()
	f := &Findings{Root: t.TempDir()}
	AddCluster(f, liveInventory())
	return f, Propose(f, ProposeOptions{Name: "bookstore", Namespace: "default"})
}

func assertNoSecret(t *testing.T, what, text string) {
	t.Helper()
	for _, s := range secrets {
		if strings.Contains(text, s) {
			t.Errorf("%s holds the credential %q", what, s)
		}
	}
}

func mustJSON(t *testing.T, v any) string {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// TestNoCredentialIsWritten feeds a manifest, a ConfigMap and a live pod
// spec that hold passwords in plain, and checks everything discover writes
// or prints.
func TestNoCredentialIsWritten(t *testing.T) {
	f := scanProduction(t)
	assertNoSecret(t, "findings of the repository", mustJSON(t, f))
	AddCluster(f, liveInventory())
	assertNoSecret(t, "findings with the cluster", mustJSON(t, f))
	p := Propose(f, ProposeOptions{Name: "bookstore", Namespace: "default"})
	assertNoSecret(t, "proposal", mustJSON(t, p))

	dir := filepath.Join(t.TempDir(), model.DirName)
	if err := WriteProposal(dir, p, f); err != nil {
		t.Fatal(err)
	}
	// every file that was written, whatever it is called
	written := map[string]string{}
	err := filepath.WalkDir(dir, func(p string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		b, err := os.ReadFile(p)
		rel, _ := filepath.Rel(dir, p)
		written[filepath.ToSlash(rel)] = string(b)
		return err
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"topology.yaml", "bindings.yaml", "evidence.json"} {
		if written[ProposedDir+"/"+name] == "" {
			t.Errorf("%s was not written", name)
		}
	}
	for name, text := range written {
		assertNoSecret(t, name, text)
		// no URL anywhere carries a user
		if i := strings.Index(text, "@"); i >= 0 {
			t.Errorf("%s holds an @, which only the user of a URL would put there: %q", name, excerpt(text, i))
		}
	}
	// evidence.json embeds the findings; they are the ones checked above
	var ev map[string]json.RawMessage
	b, _ := os.ReadFile(filepath.Join(dir, ProposedDir, "evidence.json"))
	if err := json.Unmarshal(b, &ev); err != nil || ev["findings"] == nil || ev["evidence"] == nil {
		t.Errorf("evidence.json should hold the evidence and the findings: %v", err)
	}

	// The names stay, and so do the hosts: that is what the evidence is for.
	backend := f.candidate("backend")
	if backend == nil {
		t.Fatal("no backend")
	}
	for _, name := range []string{"POSTGRES_PASSWORD", "CLICKHOUSE_PASSWORD", "CLICKHOUSE_DSN", "DATABASE_URL", "HATCHET_CLIENT_TOKEN"} {
		if _, ok := backend.Env[name]; !ok {
			t.Errorf("the name %s should be kept", name)
		}
	}
	if backend.Env["POSTGRES_PASSWORD"] != "" || backend.Env["CLICKHOUSE_PASSWORD"] != "" {
		t.Errorf("a password keeps its name and nothing else: %v", backend.Env)
	}
	if got := backend.Env["HATCHET_CLIENT_TOKEN"]; got != "secret:hatchet/token" {
		t.Errorf("a secret reference names the secret: %q", got)
	}
	if got := backend.Env["CLICKHOUSE_DSN"]; got != "tcp://signoz-clickhouse.platform:9000" {
		t.Errorf("of a DSN only the host is kept: %q", got)
	}
	if cmd := backend.Extra["command"]; !strings.Contains(cmd, "uvicorn") || !strings.Contains(cmd, "--admin-password ***") {
		t.Errorf("the command should stay readable with its credentials masked: %q", cmd)
	}
}

func excerpt(s string, i int) string {
	from, to := max(0, i-40), min(len(s), i+40)
	return s[from:to]
}

// TestEnvFromConfigMap: the connection settings live in a ConfigMap the
// Deployments load with envFrom, in a ConfigMap Kustomize generates, and
// behind a configMapKeyRef.
func TestEnvFromConfigMap(t *testing.T) {
	f := scanProduction(t)
	p := Propose(f, ProposeOptions{Name: "bookstore"})
	for _, e := range [][3]string{
		{"backend", "bookstore-db", "sql"},                            // POSTGRES_SERVER, envFrom
		{"backend", "cache", "cache"},                                 // CACHE_HOST, envFrom
		{"backend", "hatchet-engine", "grpc"},                         // HATCHET_CLIENT_HOST_PORT, envFrom
		{"backend", "bookstore-electric", "http"},                     // ELECTRIC_URL, envFrom
		{"backend", "signoz", "tcp"},                                  // OTEL_EXPORTER_OTLP_ENDPOINT, envFrom
		{"worker", "cache", "cache"},                                  // CELERY_BROKER_URL, configMapGenerator literal
		{"worker", "bookstore-db", "sql"},                             // POSTGRES_SERVER, configMapKeyRef
		{"default-queue", "worker", "queue"},                          // celery -Q default
		{"bookstore-db-primary", "bookstore-electric", "replication"}, // DATABASE_URL of the sync service
	} {
		if !hasEdge(p, e[0], e[1], e[2]) {
			t.Errorf("missing edge %s -> %s (%s)", e[0], e[1], e[2])
		}
	}
	backend := f.candidate("backend")
	if got := backend.Env["POSTGRES_SERVER"]; got != "bookstore-db-rw" {
		t.Errorf("POSTGRES_SERVER from the ConfigMap = %q", got)
	}
	// A Secret is never read: the reference is all there is.
	if got := backend.Extra["env_from"]; !strings.Contains(got, "secret:app-secrets") || !strings.Contains(got, "configmap:app-config") {
		t.Errorf("env_from = %q", got)
	}
	// A ConfigMap that is not in the repository is said, not guessed.
	dir := t.TempDir()
	writeFile(t, dir, "deploy/api.yaml", `apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: bookstore
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/bookstore/api:1
          envFrom:
            - configMapRef:
                name: elsewhere
`)
	f2, err := Scan(Options{Root: dir})
	if err != nil {
		t.Fatal(err)
	}
	if !notesContain(f2.Notes, "elsewhere") {
		t.Errorf("a missing ConfigMap should be noted: %v", f2.Notes)
	}
}

// TestEnvFromConfigMapLive: the same settings, read from the cluster.
func TestEnvFromConfigMapLive(t *testing.T) {
	_, p := liveProposal(t)
	for _, e := range [][3]string{
		{"backend", "app-db", "sql"},
		{"backend", "cache", "cache"},
		{"backend", "hatchet-engine", "grpc"},
		{"backend", "app-electric", "http"},
		{"backend", "signoz", "tcp"},
		{"app-db-primary", "app-electric", "replication"},
	} {
		if !hasEdge(p, e[0], e[1], e[2]) {
			t.Errorf("missing edge %s -> %s (%s); have %v", e[0], e[1], e[2], p.Topology.Edges)
		}
	}
}

// TestKubernetesInterpolation: a URL assembled from $(VAR) references
// yields its host, and the references never show up as a host.
func TestKubernetesInterpolation(t *testing.T) {
	f := scanProduction(t)
	p := Propose(f, ProposeOptions{Name: "bookstore"})
	if got := f.candidate("backend").Env["DATABASE_URL"]; got != "postgresql://bookstore-db-rw:5432" {
		t.Errorf("DATABASE_URL = %q, want the host the variables resolve to", got)
	}
	// the sync service takes its user and password from a Secret: unknown,
	// yet the host is in plain sight
	if got := f.candidate("bookstore-electric").Env["DATABASE_URL"]; got != "postgresql://bookstore-db-rw:5432" {
		t.Errorf("DATABASE_URL of the sync service = %q", got)
	}
	for _, l := range append(append([]Link{}, f.Links...), p.Unresolved...) {
		if strings.ContainsAny(l.Host, "$(){}") || strings.Contains(l.Host, "unresolved") {
			t.Errorf("a variable reference became a host: %+v", l)
		}
	}
}

// TestIngressIsOneEdgePerService: several paths to one Service are one
// edge from the ingress to the Service's workload, never a component.
func TestIngressIsOneEdgePerService(t *testing.T) {
	for name, p := range map[string]*Proposal{
		"repository": Propose(scanProduction(t), ProposeOptions{Name: "bookstore"}),
		"cluster":    func() *Proposal { _, p := liveProposal(t); return p }(),
	} {
		electric := map[string]string{"repository": "bookstore-electric", "cluster": "app-electric"}[name]
		var fromIngress []string
		for _, e := range p.Topology.Edges {
			if e.From == "ingress" {
				fromIngress = append(fromIngress, e.To)
			}
		}
		if len(fromIngress) != 2 || !hasEdge(p, "ingress", "backend", "http") || !hasEdge(p, "ingress", electric, "http") {
			t.Errorf("%s: the ingress should reach backend and %s once each, got %v", name, electric, fromIngress)
		}
		for _, c := range p.Topology.Components {
			if c.Type == "external" || strings.Contains(c.ID, "login") || strings.Contains(c.Label, "/") {
				t.Errorf("%s: an Ingress path became the component %q (%s)", name, c.ID, c.Type)
			}
		}
	}
}

// TestProposedIDsMatchTheSchema validates every id a proposal emits
// against the pattern of the topology schema.
func TestProposedIDsMatchTheSchema(t *testing.T) {
	proposals := map[string]*Proposal{
		"bookstore fixture":  func() *Proposal { _, p := scanFixture(t); return p }(),
		"production fixture": Propose(scanProduction(t), ProposeOptions{Name: "bookstore"}),
		"live cluster":       func() *Proposal { _, p := liveProposal(t); return p }(),
	}
	// findings from a scanner that did not mind its ids
	odd := &Findings{Root: "/srv/Book Store", Candidates: []Candidate{
		{ID: "backend:8000 /api/v1/login", Type: "external", Label: "login"},
		{ID: "Api_Gateway", Type: "workload", Label: "gateway"},
		{ID: "db", Type: "database", Roles: &model.Roles{Primary: "DB Primary", Replicas: []string{"db_r1"}}},
	}, Links: []Link{{From: "Api_Gateway", To: "db", Kind: "sql"}}}
	a := newAccumulator(&Findings{Root: odd.Root})
	for _, c := range odd.Candidates {
		a.add(c)
	}
	for _, l := range odd.Links {
		a.link(l)
	}
	a.finish()
	proposals["odd ids"] = Propose(a.f, ProposeOptions{})
	for name, p := range proposals {
		ids := map[string]bool{}
		check := func(what, id string) {
			if !idRe.MatchString(id) {
				t.Errorf("%s: %s id %q does not match %s", name, what, id, idRe)
			}
		}
		check("system", p.Topology.Name)
		for _, g := range p.Topology.Groups {
			check("group", g.ID)
		}
		for _, c := range p.Topology.AllComponents() {
			check("component", c.ID)
			ids[c.ID] = true
			for _, n := range c.RunsOn {
				check("runs_on", n)
			}
		}
		for _, e := range p.Topology.Edges {
			check("edge from", e.From)
			check("edge to", e.To)
			if !ids[e.From] || !ids[e.To] {
				t.Errorf("%s: edge %s -> %s names a component that does not exist", name, e.From, e.To)
			}
		}
		for id := range p.Bindings.Components {
			check("binding", id)
		}
		cfg := &model.Config{Topology: p.Topology, Bindings: p.Bindings, Layout: model.Layout{Components: map[string]model.Placement{}}}
		if issues := cfg.CrossCheck(); len(issues) > 0 {
			t.Errorf("%s: the proposal does not cross-check: %v", name, issues)
		}
	}
	if p := proposals["odd ids"]; !hasEdge(p, "api-gateway", "db", "sql") {
		t.Errorf("odd ids should be made valid, not dropped: %+v", p.Topology)
	}
}

// TestBindingsUseWhatWasRead: the namespace and name of the object, the
// address of the Service, the bucket the expression resolves to.
func TestBindingsUseWhatWasRead(t *testing.T) {
	f := scanProduction(t)
	p := Propose(f, ProposeOptions{Name: "bookstore", Namespace: "default"})
	spec := func(p *Proposal, id, kind string) model.ProbeSpec {
		for _, s := range p.Bindings.Components[id] {
			if s.Kind() == kind {
				return s
			}
		}
		return nil
	}
	// every Ingress object keeps its own namespace and name
	var ingresses []string
	for _, s := range p.Bindings.Components["ingress"] {
		if s.Kind() != "k8s.ingress" {
			t.Errorf("ingress bound to %s", s.Kind())
		}
		ingresses = append(ingresses, s.String("namespace")+"/"+s.String("name"))
	}
	if strings.Join(ingresses, " ") != "bookstore/web tools/adminer" {
		t.Errorf("k8s.ingress bindings = %v", ingresses)
	}
	// Hatchet and Electric answer where their Services are
	if s := spec(p, "hatchet-engine", "hatchet.health"); s == nil || s.String("url") != "http://hatchet-api.bookstore:8080" {
		t.Errorf("hatchet.health = %v", s)
	}
	if s := spec(p, "bookstore-electric", "electric.sync"); s == nil || s.String("url") != "http://electric.bookstore:3000" {
		t.Errorf("electric.sync = %v", s)
	}
	for id, specs := range p.Bindings.Components {
		for _, s := range specs {
			for k, v := range s {
				if text, ok := v.(string); ok && (strings.Contains(text, ".default") || hasPlaceholder(text)) {
					t.Errorf("%s %s: %s = %q was not read anywhere", id, s.Kind(), k, text)
				}
			}
		}
	}
	// buckets: the value of the expression, not the name of the resource
	if s := spec(p, "bookstore-attachments-bucket", "s3.bucket"); s == nil || s.String("bucket") != "bookstore-attachments" {
		t.Errorf("bucket from a variable's default = %v", s)
	}
	if s := spec(p, "bookstore-exports-bucket", "s3.bucket"); s == nil || s.String("bucket") != "bookstore-exports" {
		t.Errorf("bucket from a local = %v", s)
	}
	for id, specs := range p.Bindings.Components {
		for _, s := range specs {
			if b := s.String("bucket"); strings.Contains(b, "crm") || strings.Contains(b, "_") {
				t.Errorf("%s: the bucket %q is the name of a Terraform resource", id, b)
			}
		}
	}
	if len(p.Bindings.Components["crm-reports"]) != 0 || !notesContain(p.Notes, "crm_reports") {
		t.Errorf("a bucket that does not resolve stays unbound, with a note: %v / %v", p.Bindings.Components["crm-reports"], p.Notes)
	}
	// placeholders are not hosts
	for _, c := range p.Topology.Components {
		if hasPlaceholder(c.ID) || hasPlaceholder(c.Label) || strings.Contains(c.ID, "domain") {
			t.Errorf("a placeholder became the component %q (%s)", c.ID, c.Label)
		}
	}
	if !notesContain(p.Notes, "admin.${DOMAIN}") {
		t.Errorf("the host left out should be noted: %v", p.Notes)
	}

	// Without a Hatchet in sight nothing is invented.
	lone := &Findings{Candidates: []Candidate{{ID: "billing", Type: "scheduledjob", Label: "Billing", Extra: map[string]string{"hatchet_workflow": "billing"}},
		{ID: "electric", Type: "syncengine", Label: "Electric"}}}
	lp := Propose(lone, ProposeOptions{Namespace: "default"})
	if len(lp.Bindings.Components["billing"]) != 0 || len(lp.Bindings.Components["electric"]) != 0 {
		t.Errorf("bindings without a known address: %v", lp.Bindings.Components)
	}
	if !notesContain(lp.Notes, "billing: hatchet.workflow not proposed") || !notesContain(lp.Notes, "electric: electric.sync not proposed") {
		t.Errorf("what was left unbound should be noted: %v", lp.Notes)
	}
}

// TestBindingsLive: the cluster's own namespaces, for the run that found
// kube-system/adminer on the ingress and default on Hatchet and Electric.
func TestBindingsLive(t *testing.T) {
	_, p := liveProposal(t)
	var ingresses []string
	for _, s := range p.Bindings.Components["ingress"] {
		ingresses = append(ingresses, s.String("namespace")+"/"+s.String("name"))
	}
	if strings.Join(ingresses, " ") != "app/web kube-system/adminer" {
		t.Errorf("k8s.ingress bindings = %v", ingresses)
	}
	want := map[string]string{"hatchet-engine": "http://hatchet-api.app:8080", "app-electric": "http://electric.app:3000", "signoz": "http://signoz.platform:8080"}
	for id, url := range want {
		found := false
		for _, s := range p.Bindings.Components[id] {
			found = found || s.String("url") == url
		}
		if !found {
			t.Errorf("%s should be probed at %s: %v", id, url, p.Bindings.Components[id])
		}
	}
}

// TestRunsOn: where the pods run, or where the manifest sends them, or
// nothing.
func TestRunsOn(t *testing.T) {
	runs := func(p *Proposal, id string) string {
		c, _ := findComp(p.Topology.Components, id)
		return strings.Join(c.RunsOn, ",")
	}
	// the repository: a node selector names node-2; nothing else says a word
	p := Propose(scanProduction(t), ProposeOptions{Name: "bookstore"})
	if got := runs(p, "backend"); got != "node-2" {
		t.Errorf("backend selects node-2, runs_on = %q", got)
	}
	for _, id := range []string{"worker", "cache", "bookstore-electric", "ingress", "hatchet-engine"} {
		if got := runs(p, id); got != "" {
			t.Errorf("%s: nothing says where it runs, runs_on = %q", id, got)
		}
	}
	// the cluster: where the pods are
	_, lp := liveProposal(t)
	for id, want := range map[string]string{"backend": "node-1,node-3", "cache": "node-2", "app-electric": "node-2", "signoz": "node-3", "hatchet-engine": "", "ingress": ""} {
		if got := runs(lp, id); got != want {
			t.Errorf("%s runs_on = %q, want %q", id, got, want)
		}
	}
	// labels and taints
	nodes := []Candidate{
		{ID: "node-1", Type: "node", Name: "node-1", Labels: map[string]string{"role": "app"}},
		{ID: "node-2", Type: "node", Name: "node-2", Labels: map[string]string{"role": "db"}, Extra: map[string]string{"taints": "dedicated=db:NoSchedule"}},
		{ID: "node-3", Type: "node", Name: "node-3", Labels: map[string]string{"role": "db"}},
	}
	for _, c := range []struct{ selector, tolerations, want string }{
		{"role=db", "", "node-3"},
		{"role=db", "dedicated=db", "node-2,node-3"},
		{"role=db", "*", "node-2,node-3"},
		{"role=app|db", "dedicated", "node-1,node-2,node-3"},
		{"kubernetes.io/hostname=node-1", "", "node-1"},
		{"role=cache", "", ""},
		{"", "dedicated=db", ""}, // a toleration allows, it does not place
	} {
		got := strings.Join(runsOn(Candidate{Extra: map[string]string{"node_selector": c.selector, "tolerations": c.tolerations}}, nodes), ",")
		if got != c.want {
			t.Errorf("selector %q tolerations %q: runs on %q, want %q", c.selector, c.tolerations, got, c.want)
		}
	}
}

// TestProductIsOneComponent: the collector, the store, its coordination
// service and the agents of one observability stack are one component.
func TestProductIsOneComponent(t *testing.T) {
	check := func(name string, f *Findings, p *Proposal) {
		var obs []string
		for _, c := range p.Topology.Components {
			if c.Type == "observability" || strings.Contains(c.ID, "signoz") || strings.Contains(c.ID, "zookeeper") || strings.Contains(c.ID, "otel") {
				obs = append(obs, c.ID)
			}
		}
		if len(obs) != 1 || obs[0] != "signoz" {
			t.Errorf("%s: the stack should be the one component signoz, got %v", name, obs)
		}
		c := f.candidate("signoz")
		if c == nil {
			t.Fatalf("%s: no signoz", name)
		}
		listed := strings.Join(c.Objects, "; ") + " | " + mustJSON(t, c.Evidence)
		for _, w := range []string{"signoz-otel-collector", "signoz-zookeeper", "chi-signoz-clickhouse-cluster-0-0", "signoz-k8s-infra-otel-agent"} {
			if !strings.Contains(listed, w) {
				t.Errorf("%s: %s should be listed in the evidence of signoz: %s", name, w, listed)
			}
			if f.candidate(w) != nil {
				t.Errorf("%s: %s is still a candidate of its own", name, w)
			}
		}
		// the collector's Service now names the product
		if !hasEdge(p, "backend", "signoz", "tcp") {
			t.Errorf("%s: traces should flow to signoz: %v", name, p.Topology.Edges)
		}
	}
	f := scanProduction(t)
	check("repository", f, Propose(f, ProposeOptions{Name: "bookstore"}))
	lf, lp := liveProposal(t)
	check("cluster", lf, lp)
	// the repository first, the cluster after: still one
	AddCluster(f, liveInventory())
	check("repository and cluster", f, Propose(f, ProposeOptions{Name: "bookstore"}))
	if got := strings.Join(f.candidate("signoz").RunsOn, ","); got != "node-3" {
		t.Errorf("the product runs where its own pods run, not where every part does: %q", got)
	}

	// The application's own release is not a product: its parts stay.
	own := newAccumulator(&Findings{})
	for _, n := range []string{"api", "worker", "cache"} {
		img := "ghcr.io/bookstore/" + n + ":1"
		typ := "workload"
		if n == "cache" {
			img, typ = "redis:7", "cache"
		}
		own.add(Candidate{ID: n, Type: typ, Kind: "Deployment", Name: n, Namespace: "bookstore", Image: img,
			Labels: map[string]string{"app.kubernetes.io/instance": "bookstore", "app.kubernetes.io/part-of": "bookstore"}, Extra: map[string]string{"release": "bookstore"}})
	}
	own.finish()
	if len(own.f.Candidates) != 3 {
		t.Errorf("api, worker and cache of one release must stay three components: %+v", own.f.Candidates)
	}
}

// TestElectricBindingHasNoTable: with a table the probe asks Electric for a
// shape, and Electric answers a new shape with a snapshot query on the
// database. Discovery never proposes that.
func TestElectricBindingHasNoTable(t *testing.T) {
	_, fixture := scanFixture(t)
	_, live := liveProposal(t)
	proposals := map[string]*Proposal{"bookstore fixture": fixture, "production fixture": Propose(scanProduction(t), ProposeOptions{Name: "bookstore"}), "live cluster": live}
	for name, p := range proposals {
		seen := 0
		all := map[string][]model.ProbeSpec{}
		for id, specs := range p.Bindings.Components {
			all[id] = specs
		}
		for id, specs := range p.Bindings.Edges {
			all[id] = specs
		}
		for id, specs := range all {
			for _, s := range specs {
				if s.Kind() != "electric.sync" {
					continue
				}
				seen++
				if _, ok := s["table"]; ok {
					t.Errorf("%s: %s proposes electric.sync with table %v", name, id, s["table"])
				}
			}
		}
		if seen == 0 {
			t.Errorf("%s: no electric.sync binding to check", name)
		}
	}
	// the shapes the code reads are known (the fixtures read "issues" and
	// "items"), so leaving the table out is a choice
	if f, _ := scanFixture(t); f.candidate("electric").Extra["tables"] == "" {
		t.Error("the fixture should know a table, or this test checks nothing")
	}
}

func notesContain(notes []string, text string) bool {
	for _, n := range notes {
		if strings.Contains(n, text) {
			return true
		}
	}
	return false
}

func writeFile(t *testing.T, root, rel, content string) {
	t.Helper()
	p := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestTerraformExpressions: what a name resolves to, or nothing.
func TestTerraformExpressions(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "infra/variables.tf", `variable "domain" {
  type    = string
  default = "bookstore.example"
}

variable "environment" {
  type = string
}

variable "media_bucket" { default = "overridden-below" }

locals {
  prefix = var.environment_prefix
  zone   = var.domain
}
`)
	writeFile(t, dir, "infra/terraform.tfvars", `media_bucket = "bookstore-media"
hcloud_token = "Tf-Tok-3e1b"
`)
	writeFile(t, dir, "infra/staging.tfvars", `media_bucket = "bookstore-media-staging"
`)
	writeFile(t, dir, "infra/main.tf", `resource "cloudflare_record" "app" {
  name    = "app.${var.domain}"
  content = "203.0.113.10"
}

resource "cloudflare_record" "env" {
  name    = "${var.environment}.bookstore.example"
  content = "203.0.113.10"
}

resource "cloudflare_record" "api" {
  name      = "api"
  zone_name = local.zone
}

resource "minio_s3_bucket" "crm_media" {
  bucket = var.media_bucket
}

resource "minio_s3_bucket" "crm_logs" {
  bucket = "${local.prefix}-logs"
}

module "network" {
  source = "git::https://deploy:Tf-Git-Pa55-7c2d@git.bookstore.example/infra/network.git"
}
`)
	f, err := Scan(Options{Root: dir})
	if err != nil {
		t.Fatal(err)
	}
	p := Propose(f, ProposeOptions{Name: "bookstore"})
	for _, id := range []string{"app-bookstore-example", "api-bookstore-example", "bookstore-media-bucket"} {
		if !hasComp(p, id, "") {
			t.Errorf("%s should resolve: %+v", id, p.Topology.Components)
		}
	}
	for _, c := range p.Topology.Components {
		if strings.Contains(c.ID, "environment") || strings.Contains(c.ID, "var") || hasPlaceholder(c.Label) {
			t.Errorf("an expression became the component %q (%s)", c.ID, c.Label)
		}
	}
	if specs := p.Bindings.Components["bookstore-media-bucket"]; len(specs) != 1 || specs[0].String("bucket") != "bookstore-media" {
		t.Errorf("terraform.tfvars wins over the default, and staging.tfvars is not read: %v", specs)
	}
	if len(p.Bindings.Components["crm-logs"]) != 0 || !notesContain(p.Notes, "crm_logs") || !notesContain(p.Notes, "cloudflare_record.env") {
		t.Errorf("what does not resolve is left unbound and noted: %v", p.Notes)
	}
	out := mustJSON(t, f) + mustJSON(t, p)
	for _, s := range []string{"Tf-Tok-3e1b", "Tf-Git-Pa55-7c2d", "deploy:"} {
		if strings.Contains(out, s) {
			t.Errorf("%q was kept", s)
		}
	}
	if !notesContain(p.Notes, "git.bookstore.example") {
		t.Errorf("the module's source keeps its host: %v", p.Notes)
	}
}
